- Error(Exception) Handling: try -> catch -> finally
  - try : 에러 발생할 수 있는 부분 시도
  - catch : 에러를 잡는다
  - finally : 에러가 발생하든 안하든 마무리 단계

```tsx
function readFile(fileName: string): string {
  if (fileName === "존재하지 않음") {
    throw new Error(`파일 이름이 존재하지 않음 : ${fileName}`);
  }
  return "파일 컨텐츠";
}

function closeFile(fileName: string) {}

const fileName = "file";
console.log(readFile(fileName)); // 파일 컨텐츠 라고 출력됨.
closeFile("file");
```

- 에러 발생 시킬 경우
  - 어플리케이션이 동작을 멈춘다.
  - 에러의 이유와 에러가 발생한 위치를 알려준다
  - Error 이라는 에러 메시지를 알려준다.

```tsx
...
const fileName2 = "존재하지 않음";
console.log(readFile(fileName));
closeFile("file");
```

```tsx
/home/jhc/typescript/8-exception/8-1-exception.ts:13
    throw new Error(`파일 이름이 존재하지 않음 : ${fileName}`);
          ^
Error: 파일 이름이 존재하지 않음 : 존재하지 않음
```

- 에러가 발생해도 어플리케이션이 죽지 않게 하는 방법
  - try - catch 문을 사용하여 방지한다.
  - **catch문 안에 어떠한 문제가 생겼는지 적어주면 좋다.**

```tsx
function readFile(fileName: string): string {
  if (fileName === "존재하지 않음") {
    throw new Error(`파일 이름이 존재하지 않음 : ${fileName}`);
  }
  return "파일 컨텐츠";
}

function closeFile(fileName: string) {}

const fileName = "존재하지 않음";
// 에러가 정확히 생길 수 있는 부분에서만 try를 사용한다.
try {
  console.log(readFile(fileName));
} catch (error) {
  console.log("에러를 잡음!");
}
```

- 출력값 :

```tsx
에러를 잡음!
```

- 에러가 발생해도 해야할 동작이 있다면 **finally**를 사용하면 된다.
- **예시 동작 과정**
  - try : 파일을 읽기위해 연다.
  - catch : 파일에 오류가 생기면 에러가 생겼다고 알린다.
  - finally : 다음 동작을 위해 파일을 닫는다.

```tsx
...

try {
  console.log(readFile(fileName));
} catch (error) {
  console.log("에러를 잡음!");
} finally {
  closeFile(fileName);
	console.log("파일을 닫습니다");
}
```

- 출력값
  - 에러가 발생해도 문제없이 파일을 닫는 과정이 진행된다.

```tsx
에러를 잡음!
파일을 닫습니다
```
